### ISSUE TITLE
Add feature for GitHub key update

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#22]
On first login itself, the user would be provided with a prompt to set up their GitHub public key.

It could be something like

``` bash
To make pushing code to GitHub easier, we would go ahead and setup your GitHub access keys now. Would you like to proceed? Type (Y)es or (N)o.
```

If user says `No`, or hits <kbd>n</kbd> or <kbd>N</kbd>, skip the process. Print out how you can do this in the future by maybe running some command.

If user just hits <kbd>Enter</kbd> or <kbd>Y</kbd> + <kbd>Enter</kbd>; go ahead and ask for email ID. If it's not a valid email ID, or GitHub returns some error saying ID not found; ask again. Do this in a loop.

If user hits <kbd>Ctrl + C</kbd> or <kbd>Cmd + C</kbd>; just print a prompt asking if they are sure they want to exit. We need this to set some value in some hidden file to ensure we don't bother the user again on next login.

If everything works successfully, clearly print out what file you changed, and how the user can now push to his repos with just command without any password.

**Comment by byteknacker** [comment]
Beautiful, would be an honour to take this up. Really wish to see how I can make secure and yet automated authentication.

**Comment by byteknacker** [comment]
@alayek should this prompt of uploading a key or giving password for Github be just after hitting vagrant up first time or after the provisioning process upon vagrant ssh?

**Comment by alayek** [comment]
@byteknacker preferably once you `vagrant ssh`

**Comment by byteknacker** [comment]
So that would work for both zeus and vagrant up version of initial setup. So once vagrant ssh into the VM, there is this prompt but what if the user says no, next time when the user ssh again there should be no such a prompt right? But what if the user decides to have Github integration after all during the second or third time of vagrant ssh login?

**Comment by alayek** [comment]
Yea, as mentioned in the issue itself, when the user says no, tell him to execute a command within the ssh session if they want to ever activate this again. As in put a script in a hidden directory under the vagrant home, then make it executable, and add it to path.

**Comment by byteknacker** [comment]
Ok perfect, that is doable. @alayek I have another issue, can you remember that when I use zeus.py it will not directly take me to /vagrant? I am not sure why, I know you explained it last time in another threat but I just did not get it. Would you mind tell me more in detail about it? The error has something to do with /vagrant/.bashrc not detected.

**Comment by byteknacker** [comment]
@alayek also I just noticed that if the user set up 2-step verification, then the user needs instead of the password an API token. This needs to be generated via Github website. If the user does not have it, it is a trivial case of username and password. I need to implement this use case as well.

**Comment by byteknacker** [comment]
I am done with this with #34
