### ISSUE TITLE
One shot Heroku Deployment via Git hooks

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#23]
The user should be able to push code to GitHub once local testing succeeds. We can set up a web hook for this in GitHub account of the user.

Once travis tests succeed, the latest commit would get automatically updated on heroku.

I am not sure about the details on this one, so we need to chalk out these.

@koustuvsinha Want to work with me on this?

**Comment by koustuvsinha** [comment]
@alayek sure. will need to plan this up!

**Comment by byteknacker** [comment]
This is extremely desirable since it will save tonnes of time, imagine how many times over you will push to heroku anyways, if you can automate a streamlined version from development finish to deployment it will be a bliss.

**Comment by byteknacker** [comment]
I really suggest that this should move to the next release as it is already very easy to login to heroku and just start deploying there. To integrate github, ci testing and heroku takes at least a week for me to do it. I think the project now with my latest PR should be finished for the first release, then we can ask for official feedback from people in the fcc user community/

**Comment by byteknacker** [comment]
Ups, please have a look at this and close it @alayek or @koustuvsinha I did it by mistake.

**Comment by alayek** [comment]
After discussion with @koustuvsinha, this is one feature we would like to solidify with our vagrant. This would surely make our June 4 demo that much exciting! Because we would focus on demonstrating end-to-end how we use this vagrant box for building web app and deploying them.

**Comment by byteknacker** [comment]
@alayek do you think you can realistically finish this issue by 4th June? That would be really awesome as I really wish to use this feature myself.
1. Github push 
2. CI testing
3. If test is passed, then Heroku push deploy

That is what I personally need.

**Comment by alayek** [comment]
No, not all of them. But maybe the Heroku push. If we cannot, we will move it to our next minor release, 0.2.0

**Comment by byteknacker** [comment]
Ok, I think we really should leave this to the next release and focus on the other features which are more pressing. This could be quite intricate.

**Comment by byteknacker** [comment]
If this is to be achieved solely via the commandline, then my current idea is that it can only be done using the combination of APIs from Github and Heroku. I am not sure if Heroku has a public API.
