### ISSUE TITLE
Create Windows Installer Script

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#24]
There should be an installation script for Windows users, that installs the following. If these are already in the correct version, skip the install. Otherwise, if older version is installed, uninstall and reinstall the correct version.
- [ ] Virtualbox 5.0.20 (latest)
- [ ] Virtualbox extension pack for latest VBox
- [ ] Vagrant 1.8.1
- [ ] Git Bash latest

Once all these are installed, run `vagrant up` from inside powershell (where the script is being executed) or Git Bash.

And finally open Git Bash and clearly print out that the user needs to run `vagrant ssh` from inside Git Bash (this command won't work from inside Windows cmd or powershell).

**Comment by alayek** [comment]
@waliahimanshu want to take this up?

**Comment by waliahimanshu** [comment]
okay I will sort this out.

**Comment by waliahimanshu** [comment]
Couple of questions 
1) Power-shell 3.0/Chocolatey need .Net 4 or higher, do we assume this is already installed ?
2) Is it okay to assume above dependencies are only installed at c:\program files ? They could be installed anywhere else as well ?

**Comment by raisedadead** [comment]
For starters we cannot assume those, however depending upon the packaging/licencing restrictions we 1) We may trigger installations prompts for .NET
2) These could be any where depending upon the user's config, so we should check the %PATH% environment variable if we can get hold of the dependencies.

**Comment by byteknacker** [comment]
How is the progress so far on this issue?

**Comment by waliahimanshu** [comment]
I have the basic script to detect packages and install if required.
I am working on uninstalling the older version if installed, as i am testing this it sometimes triggers restart of user machine, also it gets tricky because any of the packages could be installed as `msi` or `exe`.

**Comment by byteknacker** [comment]
How about try to make the code with functions and then test each function separately so as to separate causation. For each function, it should do one thing very well but very limited so it is stable. Try to hard code for all the installed application for now. We make a more general one later. Just focus on the three or four installations.

**Comment by dragon788** [comment]
I would suggest using chocolatey installed via an elevated batch file and then running the other package installs through chocolatey as it can already detect if packages are installed anywhere in the path and resolve conflicts. I could write an example if you are interested as I'm going to be doing something similar for my dotfiles repo.

**Comment by alayek** [comment]
@dragon788 sure, we could try that way. If you can write one, please discuss with @waliahimanshu and raise a PR. Thanks!

**Comment by waliahimanshu** [comment]
@dragon788  yes thanks i am using choclatey, will raise a PR soon. Review, suggestions welcome.

**Comment by byteknacker** [comment]
@dragon788 would you like to join our slack channel to chat with existing collaborators in real time? We have more resources there stored. And we could really use your guidance!

**Comment by dragon788** [comment]
You guys should check out Boxstarter, it can do all this in a single URL, its amazing.

**Comment by byteknacker** [comment]
@dragon788 great tip! That might just do our job.
