### ISSUE TITLE
Add More Tests

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#26]
At present we have only about 8 tests. We still need tests to see:
- [ ] Django integrates with Postgres nicely. That we can perform CRUD operations. Might have to write some fixtures.
- [ ] Heroku one-shot deployment works
- [ ] GitHub keys can be set up

Other than this, we need tests for a few other stuff along the way.

**Comment by byteknacker** [comment]
Also note that you can just run pip freeze within the tester to see and match the result with the desired state.

**Comment by alayek** [comment]
I am updating this to version 0.1.1 feature, because resolution of some of these would lead to a better, tightly coupled demo on June 4th.

**Comment by byteknacker** [comment]
Many thanks for taking this up.
