### ISSUE TITLE
Integrate with CI

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#27]
It's difficult to manually test stuff. Even though we have lot of reviewers, we should always have some automated CI testing.

We already tried with Travis CI. But because they are running in OpenVZ container themselves, it is not possible to install a virtualbox on top of that.

We have a few alternartives
- A private VPS
- AWS instance
- Jenkins

Would need to look at these and come up with a solid strategy of CI testing.

@raisedadead wanna take this up?

**Comment by alayek** [comment]
@zcassini @raisedadead you guys might be interested in it.

**Comment by byteknacker** [comment]
@alayek I just wish to ask that to the best of your knowledge, Travis CI is definitely no go? I am wondering though, because Vagrant source code itself has Travis CI as CI tester. https://github.com/mitchellh/vagrant

**Comment by alayek** [comment]
Thanks for pointing this out. I will check that out.

**Comment by mtancoigne** [comment]
Yes but vagrant source code id different of a vagrant running machine... I think their tests only test the vagrant software, not the running boxes.

**Comment by byteknacker** [comment]
Would it be possible to test the vagrant software plainly and our code without virtualisation? @mtancoigne

**Comment by koustuvsinha** [comment]
We can look into [this blog post](https://stefanscherer.github.io/automate-building-vagrant-boxes-with-atlas/) about how to setup via packer, CircleCI and Atlas. The final output should be auto hosted in Atlas

**Comment by raisedadead** [comment]
@koustuvsinha awesome share. I have been wondering in the wild, for a work around. This seems promising.

**Comment by koustuvsinha** [comment]
@raisedadead we need to _packerize_ all of our setup first. check the repo associated with this blog

**Comment by alayek** [comment]
@raisedadead are you willing to take this up?

**Comment by alayek** [comment]
Thanks @raisedadead :smile:

**Comment by raisedadead** [comment]
In parts yes, I'll see what I can do, but don't kick me if I can't! :tongue:

**Comment by mtancoigne** [comment]
> Would it be possible to test the vagrant software plainly and our code without virtualisation?

@byteknacker I don't think so

**Comment by alayek** [comment]
@raisedadead the milestone for this is our next to next release - June 30th. You have plenty of time till then :smiley_cat:
