### ISSUE TITLE
Nice and Non-conflicting Name for Vagrant VM

### ISSUE THREAD

**Issue by byteknacker** [DevBlend/zenias#29]
When vagrant up is run and the VM is provisioned, the VM shall receive a nice nickname such as fcc-vm-1. This is to make it much easier to search the box inside vagrant global-status and delete it by name instead of a hash code. 

There should be no conflict of names when multiple environments are setup. If there are more than one VM on the same local machine, then change the name of the VM subsequently using a numbering or sequence system. The system is yet to be determined but should be automatic.

**Comment by byteknacker** [comment]
@alayek I think we should put this for the next release and not this one. What do you think?

**Comment by byteknacker** [comment]
This is a nice feature but not important. We may leave it to later.

**Comment by mtancoigne** [comment]
And the name shoudl be `fcc-box-<language>-<x>` or `fcc-<language>-box-<x>` or whatever with the language in addition to a number

**Comment by byteknacker** [comment]
I think box is redundant, how about just fcc-<stack>-<number>, where number will distinguish multiple instances of zeus vm. Let's call multiple sessions instances. So if you launch vagrant with zeus, then you create an instance of a zeus vm or something like that just for our jargon...
