### ISSUE TITLE
Python Version?

### ISSUE THREAD

**Issue by zoeyronain** [DevBlend/zenias#3]
Hey guys,

Is there a particular reason why you are picking python 3 for the project? from the little bit that I've read about python 3, it's still better to use version 2 (granted I take what "Learn Python the Hard Way" with a grain of salt.) Python 2 has a lot more package support, and a lot of what is in Python 3 isn't able to be backported to Python 2. Thoughts?

**Comment by byteknacker** [comment]
Yes that is true, we may even wish to make it Python 2 and 3 compatible but it was not really a conscious choice for Python 3 rather, a habit of beginning new projects in 3 and not in 2. I think it should not be too much of a problem. Also zeus.py is in python 2. Python 3 is only there if you need it in the dev environment.

**Comment by alayek** [comment]
According to official [Python documentation](https://wiki.python.org/moin/Python2orPython3), Python 3 is best bet, unless you are supporting legacy application.

> This means that all recent standard library improvements, for example, are only available by default in Python 3.x.

I have talked with a few domain experts who have been working on Python in industry for a few years (as in, their day job is to write code in Python for various system maintenance, data science and web development). They share the same thoughts.

I would be happy to see some counterargument in favor of Python 2 over Python 3.

**Comment by byteknacker** [comment]
Let's write new stuff for Python 3 except for scripting such as zeus since most people still have python 2 as a default. Once we packaged it for pip it should not matter.
