### ISSUE TITLE
File Not Fund and Several Other Errors

### ISSUE THREAD

**Issue by byteknacker** [DevBlend/zenias#37]
Currently I have no idea why this happens. I am using the master branch of the release Version 0.1.0

Happened at the end of provisioning and using zeus.py.

<img width="647" alt="1__developer__ssh_" src="https://cloud.githubusercontent.com/assets/10653912/15567766/7810aecc-2328-11e6-85cd-c20b27b52c57.png">

**Comment by byteknacker** [comment]
This is not persistent. When I ran exactly the same command again, everything was fine.

**Comment by alayek** [comment]
Yes, I noticed this once or twice, but in my case, it was because power cut in between provisioning. Some packages were not retrieved, and later packages needed them.

At any rate, user won't see any of these errors, once we pack the final provisioned box and host on hashicorp publicly.

**Comment by byteknacker** [comment]
Ok I guess this would be not a big deal for now. Shall we keep this open or close it?

**Comment by alayek** [comment]
No, I want to inspect it more closely. Please keep it open.

**Comment by byteknacker** [comment]
@alayek any progress on the inspection of this issue?

**Comment by alayek** [comment]
I have used the provisioner a few times since I reported this. I haven't been able to reproduce this. I might keep it open until 0.1.1 release.

**Comment by byteknacker** [comment]
Ok sure.

**Comment by byteknacker** [comment]
May I close this one and we can reopen it again if it reappears.
