### ISSUE TITLE
Using Packer to Publish as Custom Box

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#38]
Client side provisioning can go wrong at times, with fluctuating internet connection etc. It is better to package the whole box and host on Hashicorp as a public box.

We still need provisioning with shell script or Chef to help collaboorators tweak and have those tweaks reviewed in a reproducible manner. We would also need this for CI.

However, the end user doesn't need this.

With every release, we can set up a Git Hook to automatically provision, apply packer on the provisioned environment, and push to Hashicorp.

**Comment by alayek** [comment]
Any takers?

**Comment by byteknacker** [comment]
@alayek are you saying that for each of the pre-configured stack, we have a static box hosted on Hashicorp, when people use zeus, they will download these boxes instead of running the provisioner? That is agreeable. I think this will fasten speed massively since they don't have to run the provisioner every single time but once the box is downloaded, it will be just within a minute to launch the entire vagrant up.

**Comment by byteknacker** [comment]
@alayek this will take some time as we need to configure atlas, github, packer all in a orchestrated way. We may also need consul from hashicorp so it is not a trivial matter. I doubt that this can be realistically done before the Version 0.2.0.

**Comment by mtancoigne** [comment]
Agreed, provisionning time may be long the first time, but take a look at [vagrant-cachier](https://github.com/fgrehm/vagrant-cachier), a plugin for vagrant that share dependencies amongst same machines... So the first setup will be long, the second may be shorter... I added it in the [PHP Vagrantfile](https://github.com/alayek/zeus/blob/master/php/Vagrantfile#L53).

That can be a first approach to reduce provisionning time until we set up things with Hashicorp

**Comment by byteknacker** [comment]
@mtancoigne well done! Thanks for adding this plugin. I take a look now and see if we can do it for the entire project.

**Comment by byteknacker** [comment]
@mtancoigne I found out about this: https://github.com/fgrehm/vagrant-cachier/issues/143

The guy who started this cannot maintain it anymore and is looking for someone else to do it. I am not sure if the release is stable.

**Comment by mtancoigne** [comment]
It's still used in puphpet boxes, so i think there is no problem for now
