### ISSUE TITLE
Integrating Other Environment Provisioning within Zeus

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#39]
We started with Python, but it was always meant to be extended to other environments (Rails, Node & Express, Elixir etc.)

Here are the key points we would want to keep in mind:
- an end user should be able to get only one environment as they need.
- provisioning logic for all of these would be in this directory.

A lot of efforts need to be duplicated if we keep these repos separate - where only difference would be in specific provisioning packages. Hence we have to think of a way to integrate those provisioning logic within this repo itself.

This issue can be closed with the first pull request that re-architects the directory structure to handle multiple provisioners, and some variable in Vagrantfile to handle the switch-case logic.

**Comment by byteknacker** [comment]
@alayek I take up this issue and will finish the architecture planning and implementation with the current stack available.
