### ISSUE TITLE
Vagrantfile syntax error with ubuntu/xenial64

### ISSUE THREAD

**Issue by zoeyronain** [DevBlend/zenias#4]
hacktop:fcc-python-vagrant zoeycluff$ vagrant up
There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/Users/zoeycluff/fcc-python-vagrant/Vagrantfile:13: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    config.vm.provision :shell, :path => "provision.sh"
                                                   ^
/Users/zoeycluff/fcc-python-vagrant/Vagrantfile:13: unterminated string meets end of file
/Users/zoeycluff/fcc-python-vagrant/Vagrantfile:13: syntax error, unexpected end-of-input, expecting keyword_end

the vagrant file is: (I've tried it with ubuntu/xenial64 and ubuntu/xenial32)

>  # -_\- mode: ruby -_-
> # vi: set ft=ruby :
> 
> Vagrant.configure("2") do |config|
>     # Start with base vagrant box. This one is only 271 MB in size.
>     config.vm.box = "ubuntu/xenial64”
> 
> ```
> # Create forwarding ports for client-guest machine access via localhost.
> config.vm.network :forwarded_port, guest: 80, host: 8080
> config.vm.network :forwarded_port, guest: 8000, host: 8000
> 
> # Provision the virtual machine.
> config.vm.provision :shell, :path => "provision.sh"
> ```
> 
> end

**Comment by byteknacker** [comment]
So you did not get this when trying using the ubuntu/trusty64? Did you have this box pre-installed?

**Comment by zoeyronain** [comment]
No error with ubuntu/trusty64. I have the box preinstalled. I didn't get the same error on my laptop (it spit out an error about vt_d)

**Comment by alayek** [comment]
Looks like an error with the line

> ``` ruby
> config.vm.provision :shell, :path => "provision.sh"
> ```

So check the previous line.

**Comment by byteknacker** [comment]
It might be the case that you need to add the url of this particular new box to your vagrantfile. Syntax error is strange though.

**Comment by zoeyronain** [comment]
This appears to be related to an issue with OS X. Just tried it on windows and it worked successfully.

**Comment by byteknacker** [comment]
Did you install the newest Ruby version on Mac? I am using mac OS and it works. What OS system are you using and what version?

**Comment by zoeyronain** [comment]
OS X 10.11.4, and I do not have the newest version of ruby. I'll try upgrading it the next time I'm on it.

**Comment by byteknacker** [comment]
Ok I think this might have been the issue. Ruby needs to be updated for vagrant's new version to work.

**Comment by byteknacker** [comment]
Also try to update Vagrant

**Comment by byteknacker** [comment]
@siadevelopment did you manage to test further on xenial? Not sure if it works out. I do apologise for not merging your Pull Request.
