### ISSUE TITLE
Instant Boot with Torrent Streaming

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#40]
There are several projects written using Node JS based Torrent streaming to somehow _stream_ a provisioned box.

For Docker images, there is [Torrent - Docker](https://github.com/mafintosh/torrent-docker) project, and for regular ISO images, there is [Torrent - Mount](https://github.com/mafintosh/torrent-mount).

We need to check these projects and create our own npm module or some kind of extension that works with Vagrant boxes.

Obviously, this requires the client machine at least has Node JS, but that's more than compensated by the fact that now the boot up would be instant, even if the box **is not fully downloaded** on client's machine. It also requires there be some seed available (at least one) for the client to use.

It is surely worth looking into!

**Comment by byteknacker** [comment]
This should be one of the top issues as it will increase massively the likelihood of zeus being used by more people.
