### ISSUE TITLE
Add test and production flags to zeus

### ISSUE THREAD

**Issue by byteknacker** [DevBlend/zenias#48]
Users wish sometimes to test and sometimes to do the apps in production mode. If they test Zeus then the test directory should be copied by Zeus to the synced folder of VM. Add flags for these two modes for Zeus create

**Comment by alayek** [comment]
I have assigned the two of us to work and resolve this issue, then test it thoroughly.

**Comment by mtancoigne** [comment]
For the PHP box, all a user have to do to switch from one to the other is to change a var in a file to turn of debug mode in CakePHP. That debug mode will turn off all dev settings and plugins, wich is a simple and elegant solution to test the production mode. Even the DB can be switched too.

**Comment by byteknacker** [comment]
@mtancoigne I think I can programmatically hook it with bash from zeus source code, so user don't have to change the file themselves.

**Comment by mtancoigne** [comment]
@byteknacker you switch from dev to prod in order to see your work. Leave this to the user, please :)
Here is the flow :
- Start the box
- Code
- Switch to prod environment
- See if if it's fine
- Switch to dev
- Code
- ...
- Push to heroku

The production environment switch is part of the flow, the user changes it to live test his changes. No need to reload the box or something.

**Comment by mtancoigne** [comment]
@byteknacker My bad, I re-read carefully the issue and I was wrong. You want a box where you can tests Zeus, and I thought you wanted the ability to launch _all_ the boxes in a dev or prod state so user can test his code in dev or prod...

**Comment by byteknacker** [comment]
@mtancoigne no worries but you accidentally made an excellent point. This work flow you suggested is exactly the one used by otto from HashiCorp. You really should try it out, it is dead simple to use and amazing. But it lacks the customisation we need. So my question is, how do you want the production mode to be? Wouldn't it suffice to just push it to Heroku and this would be the production mode rather than having a production mode built? It is extremely difficult to do it unless we use Terraform and AWS and not everyone wants to have AWS since you need to put your credit card details there.

**Comment by byteknacker** [comment]
I need to begin the restructuring of test directories. This will change the structure of our code a little bit.
