### ISSUE TITLE
Ruby box vagrant bootup too slow

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#50]
I don't know if there is any way to speed this up with Chef itself. If we cannot fix this with Chef, we might need to switch to Shell Script provisioning.

Notice that Chef cookbook has introduced over 330 files that has made this whole repository massively Ruby-rich. Not that I am against Ruby, but this would be a huge burden on the end user.

We need to come up with a solution that requires only the bare minimum, and if we cannot do that with Chef, we will explore other solutions.

**Comment by byteknacker** [comment]
Is it possible to reduce and customise on top of existing chef cookbooks?

**Comment by zcassini** [comment]
I've changed package managers in pr #54 
This takes the cookbooks out of the repo while only taking on a lil wait to the vagrant up time.

It does take longer to get to the meat of provisioning tan the vagrant box but only about 60 secs on my machine.

All the cookbooks are opensource so we can absolutely fork them to our needs.

**Comment by byteknacker** [comment]
Ok, I think we may want to overwrite some of their installs to cut everything to the bare minimum. I have a great urge now to switch to docker asap.

**Comment by zcassini** [comment]
#65 should close this issue.
