### ISSUE TITLE
Node box is missing packages

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#51]
The Nodebox needs to be fixed and more tuned towards having packages that our campers would typically need for doing the back-end projects and API projects. 

The workshopper modules can be removed. We can also look at the existing repository under fcc-org and keep core-packages.

**Comment by koustuvsinha** [comment]
which packages should we target @alayek ?

**Comment by alayek** [comment]
@koustuvsinha :point_up: [June 1, 2016 2:11 PM](https://gitter.im/FreeCodeCamp/vagrant?at=574e9fc46bbc2d1d4df015bf)
