### ISSUE TITLE
Adding Tests

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#52]
Even if we cannot add continuous integration until we find a good free CI solution that would allow virtualization, we can use `bats` for shell script based testing.

The Python vagrant already has some tests written in `py.test`, so need to change that.

We need to add to other boxes similar testing that a contributor or tester would boot up their Vagrant and run the test suite. 

@byteknacker this would probably require the test suit copying, in the `development` mode you plan on using with `zeus`.

**Comment by byteknacker** [comment]
Ok, I take the part of creating an option for test mode. The default mode is not test and there is no extra name for it due to simplicity.

**Comment by zcassini** [comment]
All boxes have heroku toolbelt which installs an old version of ruby.
That gives all boxes the ability to run [minitest](http://docs.seattlerb.org/minitest/)
I'll get some tests up soon.
