### ISSUE TITLE
PHP debug/production mode : Create the production DB on server setup.

### ISSUE THREAD

**Issue by mtancoigne** [DevBlend/zenias#53]
Following #48 :
We should setup a production DB for when user switch from `debug` to `prod`, so he can test both in the same vagrant box.

**Comment by byteknacker** [comment]
@mtancoigne can you just tell me how to interphase with this switch in PHP so I will add this as a command option to zeus.

**Comment by mtancoigne** [comment]
@byteknacker I think you should leave that to the user. He will manually switch by changing a value in the Cake files, so he don't have to change the box to do so.

**Comment by mtancoigne** [comment]
After some thinking, I think it's a bad idea to have two separate DBs, because if the user forget to sync them, he will have errors... And in production, errors are not so obvious. So for now, i'll add the switch to change between dev/prod, but there will only be one DB for the user.

**Comment by byteknacker** [comment]
@mtancoigne sounds good.

**Comment by mtancoigne** [comment]
Great :)
