### ISSUE TITLE
sudo-less install of packages?

### ISSUE THREAD

**Issue by koustuvsinha** [DevBlend/zenias#6]
currently i'm trying to make postgresql work by this piece of code : 

``` sh
 sudo apt-get install -y python-dev libpq-dev postgresql postgresql-contrib
 sudo su - postgres
 sudo psql postgres -c "CREATE DATABASE fcc_project"                                                                                              
 sudo psql postgres -c "CREATE USER fcc WITH PASSWORD 'fcc'"
 sudo psql postgres -c "GRANT ALL PRIVILEGES ON DATABASE fcc_project TO fcc"
```

everytime, however, the vagrant logs out this error : 

``` sh
==> default: psql: FATAL:  role "root" does not exist
==> default: psql: FATAL:  role "root" does not exist
==> default: psql: FATAL:  role "root" does not exist
```

I think it maybe due to some permission issue. Is it because I'm installing postgresql via sudo? Should we focus on a sudo-less installation?

**Comment by byteknacker** [comment]
If you perhaps try without sudo for all lines, let me know if that would work out. In my experience you need sudo for apt-get but not for running psql. Try to do everything sudo less first and then only sudo with the apt-get.

**Comment by byteknacker** [comment]
I know the problem now, it may be the case that it is the same issue I got. You see,  sudo psql postgres -c "CREATE DATABASE fcc_project" assumes that you already have run sudo su - postgres. Now that pipeline is broken in the vagrant provisioning. It is as though you are doing sudo su - postgres and then the programmes shuts down the entire VM and logs in again to do sudo psql postgres -c "Whatever command you use."

**Comment by byteknacker** [comment]
The solution to that may be to chain they using && or |

**Comment by koustuvsinha** [comment]
ok trying that

**Comment by byteknacker** [comment]
But to be honest, I think that the line: sudo apt-get install -y python-dev libpq-dev postgresql postgresql-contrib would suffice for provisioning for the vagrant VM since you can instruct the student to run the subsequent commands later and they may be different for each user. Unless they are the very same and password is the same too.

**Comment by koustuvsinha** [comment]
same issue with &&. i think i will drop the idea of setting up an account by script and try manually

**Comment by byteknacker** [comment]
Yes, somehow it does not work with vagrant provisioning. Can you do it usually on your local machine to run a similar or identical script to automatically create a user on postgres?

**Comment by koustuvsinha** [comment]
trying that..
