### ISSUE TITLE
Investigate alternate base boxes for minimal size or customizability

### ISSUE THREAD

**Issue by dragon788** [DevBlend/zenias#60]
@byteknacker https://github.com/boxcutter/ubuntu is a great starting point for Ubuntu based distributions. There are other distros in the boxcutter organization as well.

There are other smaller distributions like Alpine Linux, but Vagrant support for these isn't super robust yet because it doesn't contain some of the standard Linux base components it normally hooks into.

**Comment by byteknacker** [comment]
Thanks for adding this! I will check this out.
